# dev use only
services:
  postgres:
    image: 'postgres:14.1'
    environment:
      POSTGRES_DB: 't1_data_random_coffee'
      POSTGRES_USER: 't1_data'
      POSTGRES_PASSWORD: 'coffee2024!'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
