spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/random_coffee'
    username: 'random'
    password: 'coffee2022!'
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.globally_quoted_identifiers: true

logging:
  file:
    name: randomcoffee.log
    path: ./logs/
  logback:
    rollingpolicy:
      max-file-size: 5MB
      total-size-cap: 200MB
      max-history: 3

telegram:
  name: 'InnotechRandomCoffee'
  adminId: 203918552

# UTC time by default
schedule:
  invite: '0 0 7 * * SUN'
  match: '0 0 7 * * MON'
