spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.globally_quoted_identifiers: true

telegram:
  name: 'T1DataRandomCoffeeBot '
  adminId: 203918552

# UTC time by default
schedule:
  invite: '0 0 7 * * SUN'
  match: '0 0 7 * * MON'
